// Selecting Elements;
export const _ = document;
export const openMenu = _.querySelector("#menubar");
export const closeBtn = _.querySelector("#close-btn");
export const mobileMenu = _.querySelector("#mobile-menu");
export const ul = _.querySelector("header ul");
export const indicatoreBtn = _.querySelector("#indicatore");
export const header = _.querySelector("header");
export const form = document.querySelector("#form");
export const projecstWrapper = document.getElementById("projects-wrapper");
export const skillsWrapper = document.getElementById("skills-wrapper");
